### ISSUE TITLE
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

### ISSUE THREAD

**Issue by davidcoulson** [RumenBlack84/linstor-gui-docker#3]
I am trying to reverse proxy this container through Traefik, however I get this error when loading via HTTPS:

```
Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at new WebSocketClient (webpack-internal:///./node_modules/webpack-dev-server/client/clients/WebSocketClient.js:18:19)
    at initSocket (webpack-internal:///./node_modules/webpack-dev-server/client/socket.js:35:12)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=10.2.6.93&port=8080&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true:323:55)
    at ./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=10.2.6.93&port=8080&pathname=%2Fws&logging=info&overlay=true&reconnect=10&hot=true&live-reload=true (https://linstor.domain.io/main.98da38ee86114da2d8df.bundle.js:18872:1)
    at __webpack_require__ (https://linstor.domain.io/main.98da38ee86114da2d8df.bundle.js:23005:32)
    at https://linstor.domain.io/main.98da38ee86114da2d8df.bundle.js:24113:11
    at https://linstor.domain.io/main.98da38ee86114da2d8df.bundle.js:24117:12
```

I realize the container doesn't support HTTPS transport, but is there a fix to make it work over a reverse proxy?

**Comment by RumenBlack84** [comment]
I'm not too familiar with Traefik I tend to use haproxy on my opnsense instead. However it looks like you are trying to use websockets instead of http. Can you reconfigure Traefik to attempt to connect to http on the container and present an https connection externally facing?

**Comment by davidcoulson** [comment]
Yep that is how I have it setup - My backend address is http://10.2.6.93:8080

Are you able to configure HTTPS proxy for this container with HAProxy - Would expect it works pretty much the same? Kinda curious if it works with HAProxy.
